### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by lzq920** [chenstarx/GoDB.js#1]
调用put的时候，出现```[object Object] could not be cloned```这样的错误提示，我认为应该是部分schema定义的字段数据类型是Object类型或者Array类型的问题，在业务代码调用put的时候进行一次深拷贝后调用正常，你看在```GoDB```内部是否需要处理一下

**Comment by chenstarx** [comment]
当前 Schema 内定义类型其实是没有做任何处理的（设计上是要在增删改查时做类型检查，但还没实现，优先级比较靠后），应该不是 Schema 的问题

这个问题应该是 put(obj) 的 obj 中包含一些特殊的类型，你看看 [MDN: The structrued clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)，报这个 `xxx could not be cloned` 是因为 xxx 无法被 JS 的结构化克隆算法复制，比如 Function，你尝试 put 一个 Function 进去就会报类似的错误

但我不清楚你的 obj 具体包含什么内容，导致无法被 JS 克隆，能否尝试复现一下，然后把 obj 给 log 出来看看？麻烦了

**Comment by chenstarx** [comment]
Schema 在目前的阶段只是用来给 IndexedDB 建立 objectStore (GoDB 的 Table)，以及 objectStore 内的索引时用到了，但是索引后面带的类型还没做处理，因此这个不会是 Schema 的问题

**Comment by lzq920** [comment]
@chenstarx 确实是我代码的问题，我在存储的过程中，有的数据已经变成了proxy代理对象，所以报错了，而深拷贝的过程中将这个proxy代理对象改变为了普通的对象。很抱歉，是我的问题

**Comment by chenstarx** [comment]
噢噢，是不是用的Vue3？那我可以考虑下兼容性了

**Comment by lzq920** [comment]
是的是的，正是用的vue3

发自我的iPhone
