### ISSUE TITLE
关于正式版

### ISSUE THREAD

**Issue by sunnynudt** [chenstarx/GoDB.js#3]
您好，请问godb大概啥时候可以发布正式版哈？
看到godb，希望引入到项目中使用，是对内的PC站点，技术栈是Vue 2.x + TypeScript，应该是没有兼容性问题吧？
感谢，ღ( ´･ᴗ･` )比心

**Comment by chenstarx** [comment]
Vue2 没问题的，正式版的话应该还需要一两个月

你可以先用着的，目前这个版本虽然很多特性还没加，但已经足够稳定了

如果遇到任何 bug，欢迎反馈，谢谢~
